name: Pre-Release

on:
  push:
    tags-ignore:
      - "v*"
    branches: 
      - "master"

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Packing miniz
        run: |
          mkdir pack
          cp LICENSE pack/
          cp README.md pack/
          cp -ra brs/* pack/
          cd pack 
          pip install quom
          mv brs.hpp brs-original.hpp
          python -m quom brs-original.hpp brs.hpp 

      - name: Automatic Release
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@8d9ddb2546e687f72855285d2719a11709cea6d0
        uses: marvinpinto/action-automatic-releases@v1.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            pack/LICENSE
            pack/README.md
            pack/brs.hpp
