name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
       - uses: actions/checkout@v2

       - name: "Automatic Release"
         # You may pin to the exact commit or the version.
         # uses: marvinpinto/action-automatic-releases@8d9ddb2546e687f72855285d2719a11709cea6d0
         uses: marvinpinto/action-automatic-releases@v1.1.0
         env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "latest"
           prerelease: false
           title: "Release Build"
           files: |
             LICENSE
             README.md
             brs/brs.hpp
